### ISSUE TITLE
Add boilerplate from template-for-proposals

### ISSUE THREAD

**Issue by sffc** [longlho/proposal-intl-bestavailablelocale#1]
I should have mentioned that proposal repos should be based on the following template:

https://github.com/tc39/template-for-proposals

You can add this retroactively by merging the main branch from that repo into the main branch of this one.

**Comment by longlho** [comment]
Did it do it right?

**Comment by sffc** [comment]
It looks like you merged in the files from the template repo and then deleted them.  You should make sure the files in the root of https://github.com/tc39/template-for-proposals are present in the root of this project (except for your custom README), and then follow the instructions in the README of https://github.com/tc39/template-for-proposals to set up GitHub Pages.

**Comment by longlho** [comment]
ah my bad I messed up my shell. https://longlho.github.io/proposal-intl-localematcher/ should have the "spec".

**Comment by sffc** [comment]
I think it's good now; thanks!
