### ISSUE TITLE
Move to tc39

### ISSUE THREAD

**Issue by sffc** [longlho/proposal-intl-bestavailablelocale#5]
This proposal was approved for Stage 1 on 2021-01-28.  It should now be moved to the tc39 org.  Please first transfer the repo to tc39-transfer, and then open an admin/business request for a chair to move it to tc39.

**Comment by longlho** [comment]
looks like I need permission to transfer to `tc39-transfer`?

**Comment by sffc** [comment]
You should have permissions to transfer to tc39-transfer if you are a member of tc39.  Are you a member?
